Replace and delete files
richardszalay/fastlane-plugin-act pull request #13
Opened 2018-09-16 13:39 UTC by kimdv

2018-09-16 13:40 UTC, kimdv commented
Well first attempt on learning Ruby! 
I will appreciate any feedback

2018-09-16 21:31 UTC, richardszalay commented
Looks great! Can you also add a test into `ipa_archive`? I think you'll need to move swap over to use `archive.delete` instead of `replace` for deletes in order for it to work with IPAs

2018-09-17 07:42 UTC, kimdv commented
Thanks for the feedback! 

I have added tests for `.ipa`.  And also fixed so they passes

2018-09-18 01:08 UTC, richardszalay commented
Amazing work Kim, thanks so much for taking the time contribute.

I've added a few comments onto the PR, mainly around two additional test cases. If you wouldn't mind actioning those, I'm happy to merge and release.

I actually work from Windows so am limited to what I can do. However, TravisCI will run the tests and I can publish from within WSL on Windows.

2018-09-18 05:49 UTC, kimdv commented
@richardszalay I can't see any comments? :)

2018-09-18 06:03 UTC, richardszalay commented
They should be inline in the file changes.

2018-09-18 06:08 UTC, kimdv commented
Hmm 🤔 
I’m confused now... have you added comments here on GitHub or should I add comments ? 

Because I still can’t see any. Normally they will also appear on the timeline ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2018-09-18 06:09 UTC, richardszalay commented
I've added review comments within the PR on GitHub, but not as additional commits.

2018-09-18 06:26 UTC, kimdv commented
Nope, not available for me. Are they published?

2018-09-18 06:43 UTC, richardszalay commented on lib/fastlane/plugin/act/helper/file_patcher.rb
> +          archive.extract(relative_path)
Extract isn't required here as `archive.delete` doesn't use it.

2018-09-18 06:43 UTC, richardszalay commented on lib/fastlane/plugin/act/helper/file_patcher.rb
> +          local_path = archive.local_path(relative_path)
`local_path` isn't used, so you can remove this line.

2018-09-18 06:43 UTC, richardszalay commented on spec/act_action_ipa_spec.rb
> +        it 'replace files' do
Can you create two separate tests for both app-relative and archive-relative paths work?

`replaces app-relative files` would replace "GoogleService-Info.plist" and validate against "Payload/Example.app/GoogleService-Info.plist"
`replaces archive-relative files` would replace "/Info.plist" (note forward slash prefix) and validate against "Info.plist"

2018-09-18 06:43 UTC, richardszalay commented on spec/act_action_ipa_spec.rb
> +        it 'delete files' do
Can you create two separate tests for both app-relative and archive-relative paths work?

`delete app-relative files` would delete "GoogleService-Info.plist" and validate against "Payload/Example.app/GoogleService-Info.plist"
`deletes archive-relative files` would delete "/Info.plist" (note forward slash prefix) and validate against "Info.plist"

2018-09-18 06:43 UTC, richardszalay commented on spec/act_action_xcarchive_spec.rb
> +        it 'replace files' do
See comments on ipa_archive tests

2018-09-18 06:43 UTC, richardszalay commented on spec/act_action_xcarchive_spec.rb
> +        it 'delete files' do
See comments on ipa_archive tests

2018-09-18 06:43 UTC, richardszalay commented on spec/act_action_ipa_spec.rb
> +        it 'replace files' do
Actually can you move these into their own `context`

context 'replacing files'
it 'supports app-relative paths'
it 'supports archive-relative paths'

2018-09-18 06:43 UTC, richardszalay commented on spec/act_action_ipa_spec.rb
> +        it 'delete files' do
Actually can you move these into their own context

context 'deleting files'
it 'supports app-relative paths'
it 'supports archive-relative paths'

2018-09-18 06:43 UTC, richardszalay commented on spec/act_action_ipa_spec.rb
> +        it 'replace files' do
See here for how the use of `context` makes it easier to understand in the test results: https://travis-ci.org/richardszalay/fastlane-plugin-act/jobs/429428583

2018-09-18 06:43 UTC, richardszalay commented
Ah, didn't realise you needed to submit reviews 🤷‍♂️

2018-09-19 09:32 UTC, kimdv commented
Hi @richardszalay !
Added some of you feedback! 

I don't get how the test case with `/Info.plist` should be?

Can you help me?

2018-09-19 11:02 UTC, richardszalay commented
Sure, it's not really made explicit but app paths that start with a `/` don't get prefixed by the app paths.

For those tests, the replace_files key would be `/Info.plist` and the argument passed to `invoke_plistbuddy` would just be `Info.plist`

2018-09-19 11:11 UTC, kimdv commented
So a test would look like this?

```
Fastlane::Actions::ActAction.run(
            archive_path: @ipa_file,
            remove_files: [
              "/Info.plist"
            ]
          )

          result = archive_contains("Payload/Example.app/Info.plist")

          expect(result).to be false
```

2018-09-19 11:43 UTC, richardszalay commented
Close:

```ruby
result = archive_contains("Info.plist")
```

2018-09-19 11:54 UTC, kimdv commented
Are you sure it works? 

`act_action_xcarchive_spec` fails
```
it 'deletes archive-relative files' do
          Fastlane::Actions::ActAction.run(
            archive_path: @archive_path,
            remove_files: [
              "/Info.plist"
            ]
          )

          result = archive_contains("Info.plist")

          expect(result).to be false
        end
```


`act_action_ipa_spec` fails
```
it 'deletes archive-relative files' do
          Fastlane::Actions::ActAction.run(
            archive_path: @ipa_file,
            remove_files: [
              "/Info.plist"
            ]
          )

          result = archive_contains("Info.plist")

          expect(result).to be false
        end
```

2018-09-19 11:55 UTC, kimdv commented
And sorry for all the questions!

2018-09-19 12:08 UTC, richardszalay commented
Hrm, it should! There are definitely plist-patching tests that use it. The functionality should be wrapped up in app_path / local_path, but maybe it's explicitly handled for plist patching?

2018-09-19 12:32 UTC, kimdv commented
I have no idea. It sounds like it is handled by plist_buddy :)

2018-09-19 21:07 UTC, richardszalay commented
Looks like it's handled by `ActAction` lines 22/23 but it is indeed specific to plist_path. 

Maybe it could be moved out to a new `ArchivePaths` helper class as `def self.expand(path)`? 

(`self.` assigns the function to the class rather than to an instance, similar to `static` in other languages - that way you can call it as `ArchivePaths.expand` without new'ing up an instance of `ArchivePaths`)

2018-09-20 06:50 UTC, kimdv commented
I think I got it!

2018-09-22 00:09 UTC, richardszalay requested changes
Almost there!

2018-09-22 00:09 UTC, richardszalay commented on spec/act_action_ipa_spec.rb
> +        it 'replace files' do
I think you've forgotten to remove these old tests

2018-09-22 00:09 UTC, richardszalay commented on spec/act_action_ipa_spec.rb
archive-relative tests seem to be missing for 'replacing files'

2018-09-22 00:09 UTC, richardszalay commented on spec/act_action_xcarchive_spec.rb
> +      context 'replacing files' do
The archive-relative test is missing for replace here too

2018-09-22 20:39 UTC, merged

2018-09-22 20:49 UTC, richardszalay commented
Awesome work Kim, I really appreciate your efforts.

I'll try to get a release out as soon as I can.

2018-09-24 08:48 UTC, kimdv commented
Any idea of when the release will be available 🚀

2018-09-24 10:54 UTC, richardszalay commented
I'll try within the next few days, but I'm on paternity leave with a newborn so my time is somewhat limited

2018-09-24 11:31 UTC, kimdv commented
I see! 
Congratulations ! 🎉

2018-09-25 02:33 UTC, richardszalay commented
Released as v1.2.0